<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Activation Key' => 'Chiave di Attivazione',
    'Activation key is invalid.' => 'Chiave di Attivazione non valida',
    'Activation key is missing.' => 'Chiave di Attivazione non trovata',
    'Activation key is too old.' => 'Chiave di Attivazione scaduta',
    'An email containing further instructions has been sent to email associated with specified user account.' =>
    'Un\'email contenente le istruzioni è stata inviata all\'indirizzo associato all\'.',
    'An email containing further instructions has been sent to provided email address.' =>
    'Un\'email contenente le istruzioni è stata inviata all\'indirizzo fornito.',
    'Change password' => 'Cambio Password',
    'Changes have been saved successfully.' => 'Le modifiche sono state salvate.',
    'Current password has been used too long and needs to be changed.' => 'La password corrente è scaduta e deve essere cambiata',
    'Don\'t remember username or password?' => 'Non ricordate Utente e/o Passsword?',
    'Don\'t have an account yet?' => 'Non siete ancora registrati?',
    'Email address verification' => 'Verifica email',
    'Email' => 'Email',
    'Failed to change password or log in using new password.' => 'Errore nel cambio password o nel login con la nuova password..',
    'Failed to send an email.' => 'Errrore nell\'invio della mail.',
    'Failed to log in.' => 'Errore di Login.',
    'Failed to update profile.' => 'Aggiornamento profilo fallito.',
    'Failed to verify your email address.' => 'Errroe nella verifica del vostro indirizzo email.',
    'Failed to register a new user.' => 'Errore registrazione nuovo utente.',
    'First name' => 'Nome',
    'Generate a password' => 'Genera Password',
    'Go to {link}.' => 'Vai a {link}.',
    'registration' => 'registrazione',
    'password recovery' => 'Recupero Password',
    'Try again or contact the site administrator.' => 'Tentate nuovamente o contatttate l\'amministratore',
    'Fields marked with <span class="required">*</span> are required.' => 'Campi obbligatori <span class="required">*</span>.',
    'Invalid username or password.' => 'Utente o Password errati.',
    'Last name' => 'Cognome',
    'Log in' => 'Login',
    'New password' => 'Nuova Password',
    'New password has been already used on {date}.' => 'La nuova password è stata già utilizzata {date}.',
    'New password must be different than the old one.' => 'La nuova password deve essere diversa da quella precedente.',
    'New password must contain at least 8 characters.' => 'La nuova password deve essere lunga almeno 8 caratteri.',
    'New password must contain at least one lower and upper case character and a digit.' => 'La nuova password deve contenere almeno una lettera MAIUSCOLA, una minuscola e un numero.',
    'No user found matching this email address.' => 'Non sono stati trovati utenti associati all\'indirizzo email fornito.',
    'No user found matching this username.' => 'Non sono state trovate persone con questo nome utente.',
    'Password' => 'Password',
    'Password recovery' => 'Recupero Password',
    'Password recovery has not been enabled.' => 'Il recupero Password è disabilitato.',
    'Password reset' => 'Reimposta Password',
    'Please specify username or email.' => 'Specificare il nome utente o la mail.',
    'Please type the same new password twice to verify it.' => 'Digitate due volte la nuova password per verificarla.',
    'Please wait for the account to be activated. A notification will be send to provided email address.' => 'Attendete che l\'utenza venga abilitata. Una mail verrà inviata all\'indirizzo inserito.',
    'Registration has not been enabled.' => 'La registrazione non è abilitata.',
    'Registration' => 'Registrazione',
    'Remember me when logging in next time' => 'Ricordami per il prossimo Login',
    'Submit' => 'Invia',
    'The {class} class must implement the {interface} interface.' => 'La classe {class} deve implementare l\'interfacia {interface} .',
    'This is the first time you login. Current password needs to be changed.' => 'Questa è la prima volta che vi loggate, è necessario cambiare password.',
    'Username' => 'Utente',
    'Username or password recovery' => 'Recupero Utente o Password',
    'User profile' => 'Profilo Utente',
    'Use this passowrd?\nTo copy it to the clipboard press Ctrl+C.' => 'Volete usare questa password? Usate Ctrl+C (Cmd+C su Aplle MacOS) per copiarla.',
    'Your email address has been successfully verified.' => 'Il vostro indirizzo email è stato verificato con successo.',
    'Verify' => 'Verifica',
    'update' => 'aggiorna',
    '{attribute} has already been used by another user.' => '{attribute} è stato già utilizzato da un\'altro utente.',
);
