<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Activation Key' => 'Код активации',
    'Activation key is invalid.' => 'Неверный код активации.',
    'Activation key is missing.' => 'Код активации отсутствует.',
    'Activation key is too old.' => 'Код активации устарел.',
    'An email containing further instructions has been sent to email associated with specified user account.' => 'На пользовательский email адрес отправлено письмо с дальнейшими инструкциями.',
    'An email containing further instructions has been sent to provided email address.' => 'На указанный email адрес отправлено письмо с дальнейшими инструкциями.',
    'Change password' => 'Смена пароля',
    'Changes have been saved successfully.' => 'Изменения были успешно сохранены.',
    'Current password has been used too long and needs to be changed.' => 'Текущий пароль использовался слишком долго, его необходимо сменить.',
    'Don\'t remember username or password?' => 'Не можете вспомнить имя пользователя или пароль?',
    'Don\'t have an account yet?' => 'У вас еще нет аккаунта?',
    'Email address verification' => 'Подтверждение E-Mail',
    'Email' => 'Email',
    'Failed to change password or log in using new password.' => 'Не удалось сменить пароль или войти используя новый пароль.',
    'Failed to send an email.' => 'Не удалось отправить E-Mail.',
    'Failed to log in.' => 'Не удалось войти.',
    'Failed to update profile.' => 'Не удалось обновить профиль.',
    'Failed to verify your email address.' => 'Не удалось подтвердить адрес email.',
    'Failed to register a new user.' => 'Не удалось зарегистрировать нового пользователя.',
    'First name' => 'Имя',
    'Generate a password' => 'Сгенерировать пароль',
    'Go to {link}.' => 'Перейти к {link}.',
    'registration' => 'регистрации',
    'password recovery' => 'восстановлению пароля',
    'Try again or contact the site administrator.' => 'Попробуйте снова или обратитесь к администратору сайта ',
    'Fields marked with <span class="required">*</span> are required.' => 'Поля, отмеченные <span class="required">*</span>, обязательны к заполнению.',
    'Invalid username or password.' => 'Неверная пара логин/пароль.',
    'Last name' => 'Фамилия',
    'Log in' => 'Войти',
    'New password' => 'Новый пароль',
    'New password has been already used on {date}.' => 'Новый пароль уже используется с {date}.',
    'New password must be different than the old one.' => 'Новый пароль должен отличатся от старого.',
    'New password must contain at least 8 characters.' => 'Новый пароль должен содержать минимум 8 символов.',
    'New password must contain at least one lower and upper case character and a digit.' => 'Новый пароль должен содержать хотя бы один строчный, один заглавный символ и одну цифру.',
    'No user found matching this email address.' => 'Не найдено пользователя с данным email адресом.',
    'No user found matching this username.' => 'Не найдено пользователя с таким именем.',
    'Password' => 'Пароль',
    'Password recovery' => 'Восстановление пароля',
    'Password recovery has not been enabled.' => 'Восстановление пароля не разрешено.',
    'Password reset' => 'Сброс пароля',
    'Please specify username or email.' => 'Пожалуйста укажите имя пользователя или email.',
    'Please type the same new password twice to verify it.' => 'Введите пароль и подтверждение пароля.',
    'Please wait for the account to be activated. A notification will be send to provided email address.' => 'Пожалуйста подождите пока аккаунт активируют. Уведомление будет отправлено на указанный Вами при регистрации адрес email.',
    'Registration has not been enabled.' => 'Регистрация закрыта.',
    'Registration' => 'Регистрация',
    'Remember me when logging in next time' => 'Запомнить меня в следующий раз',
    'Submit' => 'Отправка',
    'The {class} class must implement the {interface} interface.' => 'Класс {class} должен реализовывать интерфейс {interface}.',
    'This is the first time you login. Current password needs to be changed.' => 'Это Ваш первый вход в систему. Текущий пароль необходимо сменить.',
    'Username' => 'Имя пользователя',
    'Username or password recovery' => 'Восстановление имени или пароля',
    'User profile' => 'Профиль пользователя',
    'Use this passowrd?\nTo copy it to the clipboard press Ctrl+C.' => 'Использовать данный пароль? Чтобы скопировать его в буфер нажмите Ctrl+C / Cmd+C.',
    'Your email address has been successfully verified.' => 'Ваш адрес email подтвержден.',
    'Verify' => 'Подтверждение',
    'update' => 'изменить',
    '{attribute} has already been used by another user.' => '{attribute} занят(о) другим пользователем.',
);
