<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Activation Key' => 'Aktivierungs Schlüssel',
    'Activation key is invalid.' => 'Aktivierungsschlüssel ist inkorrekt.',
    'Activation key is missing.' => 'Bitte geben Sie Ihren Aktivierungsschlüssel an.',
    'Activation key is too old.' => 'Ihr Aktivierungsschlüssel ist abgelaufen.',
    'An email containing further instructions has been sent to email associated with specified user account.' => 'Eine E-Mail mit Aktivierungs intruktionen wurde an Ihre Adresse versendet.',
    'An email containing further instructions has been sent to provided email address.' => 'Eine E-Mail wurde gerade eben an Sie verschickt.',
    'Change password' => 'Passwort ändern',
    'Changes have been saved successfully.' => 'Ihre Änderungen wurden gespeichert.',
    'Current password has been used too long and needs to be changed.' => 'Ihr aktuelles Passwort ist zu lange in gebrauch bitte ändern Sie es.',
    'Don\'t remember username or password?' => 'Passwort / Username erinnern an ?',
    'Don\'t have an account yet?' => 'Sie haben sich noch nich regestriert ?',
    'Email address verification' => 'E-Mail wiederholen',
    'Email' => 'Email',
    'Failed to change password or log in using new password.' => 'Fehler beim Passwort ändern oder melden Sie sich mit Ihrem neuen Passwort an.',
    'Failed to send an email.' => 'E-Mail konnte nicht gesendet werden.',
    'Failed to log in.' => 'Login fehlgeschlagen.',
    'Failed to update profile.' => 'Ihr Profil konnte nicht erneuert werden .',
    'Failed to verify your email address.' => 'Ihre E-Mail konnte nicht erkannt werden.',
    'Failed to register a new user.' => 'Es konnte kein neuer User nagelegt werden.',
    'First name' => 'Vorname',
    'Generate a password' => 'Passwort generieren',
    'Go to {link}.' => 'Gehen Sie zu {link}.',
    'registration' => 'Regestrieren',
    'password recovery' => 'Passwort zurücksetzen',
    'Try again or contact the site administrator.' => 'Versuchen Sie es noch einmal oder informieren Sie den Administrator ',
    'Fields marked with <span class="required">*</span> are required.' => 'Pflichtfelder <span class="required">*</span>.',
    'Invalid username or password.' => 'Falscher Username oder Passwort.',
    'Last name' => 'Nachname',
    'Log in' => 'Einloggen',
    'New password' => 'Neues Passwort',
    'New password has been already used on {date}.' => 'Dieses Passwort wurde bereits schon mal genutzt {date}.',
    'New password must be different than the old one.' => 'Ihr neues Passwort muss sich zu dem alten unterscheiden.',
    'New password must contain at least 8 characters.' => 'Ihr neues Passwort muss min. 8 Zeichen lang sein.',
    'New password must contain at least one lower and upper case character and a digit.' => 'Ihr neues Passwort muss Gross, Kleinbuchstaben enthalten sowie ene Zahl.',
    'No user found matching this email address.' => 'Es existiert kein User mit dieser E-Mail adresse.',
    'No user found matching this username.' => 'Es existiert kein User mit diesem Namen.',
    'Password' => 'Passwort',
    'Password recovery' => 'Passwort wiederherstellen',
    'Password recovery has not been enabled.' => 'Passwort wiederherstellen ist nicht aktiviert.',
    'Password reset' => 'Passwort zurücksetzen',
    'Please specify username or email.' => 'Bitte geben Sie Username oder E-mail an.',
    'Please type the same new password twice to verify it.' => 'Bitte wiederholen Sie das neue Passwort.',
    'Please wait for the account to be activated. A notification will be send to provided email address.' => 'Warten Sie bitte bis Ihr Account aktiviert wurde. Eine Nachricht wurde an Ihre E-Mail versendet.',
    'Registration has not been enabled.' => 'Ihre Registration wurde noch nicht aktiviert.',
    'Registration' => 'Regestrieren',
    'Remember me when logging in next time' => 'Merken beim nächsten Login',
    'Submit' => 'Absenden',
    'The {class} class must implement the {interface} interface.' => 'Die {class} muss ein {interface} haben.',
    'This is the first time you login. Current password needs to be changed.' => 'Sie loggen sich zum ersten mal ein bitte änden Sie aus Sicherheitsgründen Ihr Passwort.',
    'Username' => 'Nazwa użytkownika',
    'Username or password recovery' => 'Username oder Passwort vergessen ?',
    'User profile' => 'User Profil',
    'Use this passowrd?\nTo copy it to the clipboard press Ctrl+C.' => 'Möchten Sie dieses Passwort verwenden dann drücken Sie bitte Ctrl+C / Cmd+C.',
    'Your email address has been successfully verified.' => 'Ihre E-Mail Adresse wurde überprüft.',
    'Verify' => 'Überprüfen',
    'update' => 'aktualisieren',
    '{attribute} has already been used by another user.' => '{attribute} wird bereits verwendet.',
);
