<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Advanced Search' => 'Szukanie zaawansowane',
  'Any' => 'Dowolnie',
  'Are you sure you want to delete this user?' => 'Na pewno usunąć tego użytkownika?',
  'Create user' => 'Utwórz użytkownika',
  'Delete user {id}' => 'Usuń użytkownika {id}',
  'Fields with {asterisk} are required.' => 'Pola oznaczone {asterisk} są wymagane.',
  'List users' => 'Przeglądaj użytkowników',
  'No' => 'Nie',
  'Update' => 'Aktualizuj',
  'Update user {id}' => 'Aktualizuj użytkownika {id}',
  'Users manager' => 'Zarządzanie użytkownikami',
  'View user {id}' => 'Szczegóły użytkownika {id}',
  'Yes' => 'Tak',
  'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.' => 'Możesz poprzedzić każdą szukaną wartość opcjonalnym operatorem porównania (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> lub <b>=</b>).',
);
