<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
  'Activation Key' => 'Klucz aktywacyjny',
  'Activation key is invalid.' => 'Klucz aktywacyjny jest nieprawidłowy.',
  'Activation key is missing.' => 'Brak klucza aktywacyjnego.',
  'Activation key is too old.' => 'Klucz aktywacyjny został wygenerowany zbyt dawno temu.',
  'An email containing further instructions has been sent to email associated with specified user account.' => 'Email zawierający dalsze instrukcje został wysłany na adres przypisany do podanego konta użytkownika.',
  'An email containing further instructions has been sent to provided email address.' => 'Email zawierający dalsze instrukcje został wysłany na podany adres.',
  'Change password' => 'Zmień hasło',
  'Changes have been saved successfully.' => 'Zmiany zostały pomyślnie zapisane.',
  'Current password has been used too long and needs to be changed.' => 'Bieżące hasło jest używane zbyt długo i musi zostać zmienione.',
  'Don\'t remember username or password?' => 'Nie pamiętasz nazwy użytkownika lub hasła?',
  'Don\'t have an account yet?' => 'Nie masz jeszcze konta?',
  'Email address verification' => 'Weryfikacja adresu email',
  'Email' => 'Email',
  'Failed to change password or log in using new password.' => 'Nie udało się zmienić hasła albo zalogować z użyciem nowego hasła.',
  'Failed to send an email.' => 'Nie udało się wysłać emaila.',
  'Failed to log in.' => 'Nie udało się zalogować.',
  'Failed to update profile.' => 'Nie udało się zaktualizować profilu.',
  'Failed to verify your email address.' => 'Nie udało się zweryfikować adresu email.',
  'Failed to register a new user.' => 'Nie udało się zarejestrować nowego użytkownika.',
  'First name' => 'Imię',
  'Generate a password' => 'Wygeneruj hasło',
  'Go to {link}.' => 'Przejdź do {link}.',
  'registration' => 'rejestracji',
  'password recovery' => 'odzyskiwania hasła',
  'Try again or contact the site administrator.' => 'Spróbuj ponownie lub skontaktuj się z administratorem serwisu.',
  'Fields marked with <span class="required">*</span> are required.' => 'Pola oznaczone <span class="required">*</span> są wymagane.',
  'Invalid username or password.' => 'Nieprawidłowa nazwa użytkownika lub hasło.',
  'Last name' => 'Nazwisko',
  'Log in' => 'Zaloguj się',
  'New password' => 'Nowe hasło',
  'New password has been already used on {date}.' => 'Nowe hasło zostało już użyte dnia {date}.',
  'New password must be different than the old one.' => 'Nowe hasło musi różnić się od starego.',
  'New password must contain at least 8 characters.' => 'Nowe hasło musi zawierać co najmniej 8 znaków.',
  'New password must contain at least one lower and upper case character and a digit.' => 'Nowe hasło musi zawierać co najmniej jedną małą i dużą literę oraz cyfrę.',
  'No user found matching this email address.' => 'Nie odnaleziono użytkownika pasującego do podanego adresu email.',
  'No user found matching this username.' => 'Nie odnaleziono użytkownika pasującego do podanej nazwy.',
  'Password' => 'Hasło',
  'Password recovery' => 'Odzysikiwanie hasła',
  'Password recovery has not been enabled.' => 'Odzyskiwanie hasła nie zostało włączone.',
  'Password reset' => 'Zmiana hasła',
  'Please specify username or email.' => 'Proszę podać nazwę użytkownika lub adres email.',
  'Please type the same new password twice to verify it.' => 'Proszę wpisać nowe hasło dwukrotnie.',
  'Please wait for the account to be activated. A notification will be send to provided email address.' => 'Proszę zaczekać, aż konto zostanie aktywowane. Powiadomienie zostanie wysłane na podany adres email.',
  'Registration has not been enabled.' => 'Rejestracja nie została włączona.',
  'Registration' => 'Rejestracja',
  'Remember me when logging in next time' => 'Pamiętaj mnie przy następnym logowaniu',
  'Submit' => 'Wyślij',
  'The {class} class must implement the {interface} interface.' => 'Klasa {class} musi implementować interfejs {interface}.',
  'This is the first time you login. Current password needs to be changed.' => 'Logujesz się po raz pierwszy. Obecne hasło musi zostać zmienione.',
  'Username' => 'Nazwa użytkownika',
  'Username or password recovery' => 'Odzyskiwanie nazwy użytkownika lub hasła',
  'User profile' => 'Profil użytkownika',
  'Use this passowrd?\nTo copy it to the clipboard press Ctrl+C.' => 'Użyć tego hasła?\nAby skopiować do schowka wciśnij Ctrl+C.',
  'Your email address has been successfully verified.' => 'Twój adres email został pomyślnie zweryfikowany.',
  'Verify' => 'Zweryfikuj',
  'update' => 'aktualizuj',
  '{attribute} has already been used by another user.' => '{attribute} został już wykorzystany przez innego użytkownika.',
);
